In [1]:
#import packages
import pandas as pd

#load data
ent=pd.read_csv('C:/Users/luisa/Documents/BIPM_2/DWH4SLR/reports/entities.csv')

ent.head()

C:\Users\luisa\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (20) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,article_id,para_id,sentence_start,sentence_id,journal_akronym,last_section_title,last_subsection_title,sentence_type,sentence,entity,...,ent_id,ent_path,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8
0,1,1_7,508,1_508_561,AMJ,Completeness,NaN,PARAGRAPH,"In the review of our decision letters , perhap...",constructs,...,construct,model element/construct,model element,construct,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1_7,594,1_594_627,AMJ,Completeness,NaN,PARAGRAPH,A good example is found in START_CITE Bommer...,group - level,...,group level,level of analysis/micro level/group level,level of analysis,micro level,group level,NaN,NaN,NaN,NaN,NaN
2,1,1_7,627,1_627_722,AMJ,Completeness,NaN,PARAGRAPH,We learn in their Methods how the participants...,20 -30 employees,...,individual participant,participant/individual participant,participant,individual participant,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1_7,627,1_627_722,AMJ,Completeness,NaN,PARAGRAPH,We learn in their Methods how the participants...,constructs,...,construct,model element/construct,model element,construct,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1_7,738,1_738_761,AMJ,Completeness,NaN,PARAGRAPH,"For example , they noted that employees and th...",questionnaires,...,survey,data collection method/empirical quantitative ...,data collection method,empirical quantitative method,survey,NaN,NaN,NaN,NaN,NaN

In [2]:
ent.columns

Index(['article_id', 'para_id', 'sentence_start', 'sentence_id',
       'journal_akronym', 'last_section_title', 'last_subsection_title',
       'sentence_type', 'sentence', 'entity', 'label', 'ent_id', 'ent_path',
       'level_1', 'level_2', 'level_3', 'level_4', 'level_5', 'level_6',
       'level_7', 'level_8'],
      dtype='object')