In [1]:
#import packages
import pandas as pd
import os

#define source directory
path='/home/muellerrol/causeminer2/reports/2021_11_09_103116_results'

#filenames of ontology stats-related files
ont_file='ontology_stats.csv'

#load data
ont=pd.read_csv(os.path.join(path,ont_file))

print(ont.shape)
print(ont.columns)

(17, 5)
Index(['Root Entity', 'Label', 'Number of Entities', 'Number of Synonyms',
       'Maximal Depth'],
      dtype='object')

In [3]:
ont.head(17)

,Root Entity,Label,Number of Entities,Number of Synonyms,Maximal Depth
0,IS topic,TOPIC,210,9695,5
1,research paradigm,PARADIGM,14,240,2
2,model element,MODEL_ELEMENT,36,202,3
3,geographic names,REGION,326,829,5
4,economic sector,SECTOR,336,2806,6
5,company type,COMPANY_TYPE,8,142,2
6,participant,PARTICIPANTS,15,242889,3
7,level of analysis,LEVEL,14,44,3
8,theory,THEORY,244,1012,4
9,data analysis method,ANALYSIS_METHOD,379,2288,9
10,sampling,SAMPLING,28,154,2
11,information systems technology,TECHNOLOGY,299,4926,5
12,conceptual method,CONCEPTUAL_METHOD,107,2671,5
13,statistical metric,METRIC,61,1752,3
14,data collection method,COLLECTION_METHOD,131,59382,6
15,numbered hypothesis,HYP,1,1340,0
16,validity,VALIDITY,24,16868,4